

// eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE3MjkyOTkxODYsImV4cCI6MTc2MDgzNTI1NywiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsImZpcnN0X25hbWUiOiJKb2huIiwibGFzdF9uYW1lIjoiRG9lIiwiZW1haWwiOiJqb2huQGRvZS5jb20ifQ.BF8aS6HtACwrv1aIdByVVCg1E8iww6xTYemnqf9pYnI

// {
//     "iss": "Online JWT Builder",
//     "iat": 1729299186,
//     "exp": 1760835257,
//     "aud": "www.example.com",
//     "sub": "jrocket@example.com",
//     "first_name": "John",
//     "last_name": "Doe",
//     "email": "john@doe.com"
// }